# ProjectBotany/docker-compose.yml
name: projectbotany
services:
  # -----------------------------------------------------------
  #  üåø ProjectBotany
  # -----------------------------------------------------------
  projectbotany-vite:
    build:
      context: ./vite
      dockerfile: Dockerfile
    container_name: projectbotany-vite
    volumes:
      - ./vite:/app:delegated
      - /app/node_modules
    networks:
      - fukaya-lab-network
    restart: unless-stopped
    command: ["yarn", "dev"]
    labels:
      caddy: http://projectbotany.app.fukaya-sus.lab # „Éâ„É°„Ç§„É≥Âêç
      caddy.reverse_proxy: "{{upstreams 5173}}"

networks:
  fukaya-lab-network:
    external: true
    name: fukaya-lab-network